services:
  - type: web
    name: aicig-final
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
