services:
  - type: web
    name: aicig-final
    runtime: python
    runtimeVersion: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: REPLICATE_TOKEN
        sync: false
